name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    env:
        primary_cloudfront_id: ${{ secrets.AWS_CLOUDFRONT_PRIMARY_ID }}
        secondary_cloudfront_id: ${{ secrets.AWS_CLOUDFRONT_SECONDARY_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_IAM_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_IAM_KEY }}
        DEST_S3_BUCKET: ${{ secrets.AWS_S3_NAME }}
        GATSBY_PRISMIC_REPO_NAME: ${{ secrets.GATSBY_PRISMIC_REPO_NAME }}
        PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
        PRISMIC_CUSTOM_TYPES_API_TOKEN: ${{ secrets.PRISMIC_CUSTOM_TYPES_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_IAM_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_IAM_KEY }}
          aws-region: us-east-1
      - name: Use Node.js 18
        uses:
          actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build
        run: |
          yarn install && yarn build && yarn deploy
      - name: Clear Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id $primary_cloudfront_id --paths "/*" && aws cloudfront create-invalidation --distribution-id $secondary_cloudfront_id --paths "/*"
