name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    env:
      primary-cloudfront-id: ${{ secrets.AWS_CLOUDFRONT_PRIMARY_ID }}
      secondary-cloudfront-id: ${{ secrets.AWS_CLOUDFRONT_SECONDARY_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses:
          actions/setup-node@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_IAM_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_IAM_KEY }}
          DEST-S3-BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          node-version: 18.x
      - name: Build
        run: |
          yarn install && yarn build && yarn deploy
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_IAM_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_IAM_KEY }}
          aws-region: us-east-1
      - name: Clear Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id $primary-cloudfront-id --paths \"/*\" && aws cloudfront create-invalidation --distribution-id $secondary-cloudfront-id --paths \"/*\"
